metadata:
    sample_annotation: sample_annotation.csv
    output_dir: $HOME/hello_looper_results

# not used, added for tesing
pipeline_interfaces:
    - $HOME/test_path
    - $HOME/test_path1
    - $HOME/test_path2

implied_columns:
    organism:
        human:
            genome: "hg38"
            macs_genome_size: "hs"
        mouse:
            genome: "mm10"
            macs_genome_size: "mm"

subprojects:
    noFrog:
        metadata:
            sample_annotation: sample_annotation_noFrog.csv
