branches:
  only:
  - master

language: bash

services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --no-cache -t databio/caravel:latest . || exit 1;
    docker push databio/caravel:latest || exit 1;
    aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/dcos-refresh' --message-body 'shefflab/caravel' || exit 1;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nem2p@virginia.edu
    - nsheffield@virginia.edu
    - mjs5kd@virginia.edu
