site_name: Caravel
site_logo: img/logo_caravel_dark.svg
site_url: http://caravel.databio.org
pypi_name: caravel
repo_url: http://github.com/pepkit/caravel

nav:
  - Getting started:
    - Introduction: README.md
  - How-to Guides:
    - How to configure caravel: configure-caravel.md
    - How to run on a remote server: remote-server.md
    - Configuring logging: logging.md
    - Changing compute settings: computing.md
  - Reference:
    - Advanced features: advanced.md
    - Usage: usage.md
    - FAQ: faq.md
    - Support: support.md
    - Contributing: contributing.md
  - Releases:
    - Changelog: changelog.md

theme: databio

navbar:
  left:
    - text: Live demo
      icon: fa-play
      href: "demo"
