metadata:
  sample_annotation: sample_annotation.csv
  sample_subannotation: sample_subannotation.csv
  output_dir: $HOME/hello_looper_results
  pipeline_interfaces: [../pipeline/pipeline_interface.yaml]

derived_columns: [file]

data_sources:
  local_files: "../data/{identifier}{file_id}_data.txt"

