metadata:
    sample_annotation: sample_annotation.csv
    output_dir: $HOME/hello_looper_results

derived_attributes: [file_path]

data_sources:
    source1: /data/lab/project/{organism}_{genome}_{condition}.fastq

implied_attributes:
    organism:
        pig:
            genome: "susScr11"
        frog:
            genome: "xenTro9"
            test:
    time:
        0:
            condition: "untreated"
        1:
            condition: "treated"
            test:
                





