name: demo
email: michal@virginia.edu
sample_table: sample_table_animals.csv
sample_modifiers:
    derive:
        attributes: [data_source]
        sources:
            path: ../../data/{filename}
    append:
        pipeline_interfaces: ../pipeline_interface.yaml
    imply:
        - if:
            protocol: slow
          then:
            sleep: 5

project_modifiers:
    amend:
        my_project2:
            sample_table: sample_table_animals_frog.csv

looper:
    output_dir: ~/Desktop/testing/caravel_demo
