metadata:
    sample_annotation: sample_annotation.csv
    output_dir: $HOME/hello_looper_results

implied_columns:
    organism:
        human:
            genome: "hg38"
            macs_genome_size: "hs"
        mouse:
            genome: "mm10"
            macs_genome_size: "mm"

          